name: Check
on:
  schedule:
    - cron: '0 0 1 1-12 *'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Get latest release from cheat
        id: get_release
        run: |
          # Fetch release information and extract the release tag
          RELEASE_TAG=$(curl -sL https://api.github.com/repos/${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}/releases/latest | jq -r '.tag_name')
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "latest release: $RELEASE_TAG"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Compare source with dest repo
        id: compare_versions
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        shell: bash
        run: |
            if [[ "${{ steps.previoustag.outputs.tag }}" == "${{ env.release_tag }}" ]]; then
                gh run cancel ${{ github.run_id }}
            fi
        
      - name: Start build    
        uses: benc-uk/workflow-dispatch@v1 
        with:
          workflow: build.yml
    
